# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_auto_20170515_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='company',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='position',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
