# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0003_auto_20170612_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connection_level',
            field=models.IntegerField(default=3),
        ),
    ]
