# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0005_auto_20170613_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocontact',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
