# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0007_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailcapture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
