# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-26 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0008_emailcapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
