# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-21 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0011_auto_20190427_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referralcode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
