# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-23 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0012_profile_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Personal', 'Personal'), ('Both', 'Both')], max_length=2, null=True),
        ),
    ]
